### ISSUE TITLE
#1 Правки

### ISSUE THREAD

**Issue by difiozy** [Liquicious/JavaTask#1]
https://github.com/Liquicious/JavaTask/blob/eb9734e3002200fbfd424dca0c84b2bd93f479c4/src/main/java/org/example/Generator.java#L6

- В джаве принято именовать переменные, методы и поля класса в camelCase
- Вместо того что бы оборачивать в try..catch каждое тело в if можно обернуть все условия разом, потому что логика дублируется в этом случае

**Comment by Liquicious** [comment]
С третьей попытки, но вроде всё пофиксил.
